HOSTED_ZONE_NAME_FOR_PROXY_DOMAINS: devpanel.me
CLUSTER_TYPE: t3.medium
CLUSTER_MIN_MACHINES: '1'
CLUSTER_MAX_MACHINES: '10'
DB_ENCRYPTION_KEY: WITHOUT
DB_SNAPSHOT: WITHOUT
DB_ENGINE: 'aurora-mysql - 5.7.12'
DB_TYPE: db.t2.small
DB_HAS_MULTIAZ: 'no'
DB_HAS_AUTOMATIC_BACKUP: 'yes'
LAMBDA_ALARM_TO_SLACK: CREATE_NEW
