#!/usr/bin/node

/*devpanel
Copyright (C) 2018 devpanel

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/



const AWS = require('/usr/lib/node_modules/aws-sdk');

let iam = new AWS.IAM();

iam.listUsers({}, (err, resultUsers) =>
{
  for (let user of resultUsers.Users)
  {
    iam.listSSHPublicKeys({UserName: user.UserName}, (err, resultPublicKeysIds) =>
    {
      for (let key of resultPublicKeysIds.SSHPublicKeys)
      {
        iam.getSSHPublicKey({UserName: user.UserName, SSHPublicKeyId: key.SSHPublicKeyId, Encoding: "SSH"}, (err, resultPublicKeys) =>
        {
          if ( (resultPublicKeys.SSHPublicKey.Status == "Active") && ((process.argv[2] + " " + process.argv[3]) == resultPublicKeys.SSHPublicKey.SSHPublicKeyBody) )
          {
            console.log(resultPublicKeys.SSHPublicKey.SSHPublicKeyBody);
            process.exit();
          }
        });
      }
    })
  }
})